[project]
name = "euler"
version = "0.1.0"
authors = [{name = "Daan Kaasjager"}]

[tool.setuptools]
packages = ["src"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
